# Automatically generated by pb2py
# fmt: off
# isort:skip_file

from typing import Optional, Sequence

from . import protobuf

class SignDigest(protobuf.MessageType):
	MESSAGE_WIRE_TYPE = 1001
	FIELDS = {
		1: protobuf.Field("address_n", "uint32", repeated=True, required=False),
		2: protobuf.Field("digest", "bytes", repeated=False, required=False),
		3: protobuf.Field("coin_name", "string", repeated=False, required=False),
	}

	def __init__(
		self,
		*,
		address_n: Optional[Sequence["int"]] = None,
		digest: Optional["bytes"] = None,
		coin_name: Optional["str"] = "Bitcoin",
	) -> None:
		self.address_n: Sequence["int"] = address_n if address_n is not None else []
		self.digest = digest
		self.coin_name = coin_name


class DigestSignature(protobuf.MessageType):
	MESSAGE_WIRE_TYPE = 1002
	FIELDS = {
		1: protobuf.Field("pubkey", "bytes", repeated=False, required=True),
		2: protobuf.Field("signature", "bytes", repeated=False, required=False),
	}

	def __init__(
		self,
		*,
		pubkey: "bytes",
		signature: Optional["bytes"] = None,
	) -> None:
		self.pubkey = pubkey
		self.signature = signature


class SignData(protobuf.MessageType):
	MESSAGE_WIRE_TYPE = 1003
	FIELDS = {
		1: protobuf.Field("address_n", "uint32", repeated=True, required=False),
		2: protobuf.Field("data", "bytes", repeated=False, required=False),
		3: protobuf.Field("coin_name", "string", repeated=False, required=False),
	}

	def __init__(
		self,
		*,
		address_n: Optional[Sequence["int"]] = None,
		data: Optional["bytes"] = None,
		coin_name: Optional["str"] = "Bitcoin",
	) -> None:
		self.address_n: Sequence["int"] = address_n if address_n is not None else []
		self.data = data
		self.coin_name = coin_name


class DataSignature(protobuf.MessageType):
	MESSAGE_WIRE_TYPE = 1004
	FIELDS = {
		1: protobuf.Field("pubkey", "bytes", repeated=False, required=True),
		2: protobuf.Field("digest", "bytes", repeated=False, required=False),
		3: protobuf.Field("signature", "bytes", repeated=False, required=False),
	}

	def __init__(
		self,
		*,
		pubkey: "bytes",
		digest: Optional["bytes"] = None,
		signature: Optional["bytes"] = None,
	) -> None:
		self.pubkey = pubkey
		self.digest = digest
		self.signature = signature


class ExportEd25519PublicKey(protobuf.MessageType):
	MESSAGE_WIRE_TYPE = 1005
	FIELDS = {
		1: protobuf.Field("address_n", "uint32", repeated=True, required=False),
	}

	def __init__(
		self,
		*,
		address_n: Optional[Sequence["int"]] = None,
	) -> None:
		self.address_n: Sequence["int"] = address_n if address_n is not None else []


class Ed25519PublicKey(protobuf.MessageType):
	MESSAGE_WIRE_TYPE = 1006
	FIELDS = {
		1: protobuf.Field("pubkey", "bytes", repeated=False, required=True),
	}

	def __init__(
		self,
		*,
		pubkey: "bytes",
	) -> None:
		self.pubkey = pubkey


class GetEd25519Nonce(protobuf.MessageType):
	MESSAGE_WIRE_TYPE = 1007
	FIELDS = {
		1: protobuf.Field("address_n", "uint32", repeated=True, required=False),
		2: protobuf.Field("data", "bytes", repeated=False, required=True),
		3: protobuf.Field("ctr", "uint32", repeated=False, required=True),
	}

	def __init__(
		self,
		*,
		data: "bytes",
		ctr: "int",
		address_n: Optional[Sequence["int"]] = None,
	) -> None:
		self.address_n: Sequence["int"] = address_n if address_n is not None else []
		self.data = data
		self.ctr = ctr


class Ed25519Nonce(protobuf.MessageType):
	MESSAGE_WIRE_TYPE = 1008
	FIELDS = {
		1: protobuf.Field("R", "bytes", repeated=False, required=True),
	}

	def __init__(
		self,
		*,
		R: "bytes",
	) -> None:
		self.R = R


class CosignEd25519(protobuf.MessageType):
	MESSAGE_WIRE_TYPE = 1009
	FIELDS = {
		1: protobuf.Field("address_n", "uint32", repeated=True, required=False),
		2: protobuf.Field("digest", "bytes", repeated=False, required=True),
		3: protobuf.Field("ctr", "uint32", repeated=False, required=True),
		4: protobuf.Field("global_pubkey", "bytes", repeated=False, required=True),
		5: protobuf.Field("global_commit", "bytes", repeated=False, required=True),
	}

	def __init__(
		self,
		*,
		digest: "bytes",
		ctr: "int",
		global_pubkey: "bytes",
		global_commit: "bytes",
		address_n: Optional[Sequence["int"]] = None,
	) -> None:
		self.address_n: Sequence["int"] = address_n if address_n is not None else []
		self.digest = digest
		self.ctr = ctr
		self.global_pubkey = global_pubkey
		self.global_commit = global_commit


class Ed25519Signature(protobuf.MessageType):
	MESSAGE_WIRE_TYPE = 1010
	FIELDS = {
		1: protobuf.Field("sig", "bytes", repeated=False, required=True),
	}

	def __init__(
		self,
		*,
		sig: "bytes",
	) -> None:
		self.sig = sig


class Ed25519Verify(protobuf.MessageType):
	MESSAGE_WIRE_TYPE = 1011
	FIELDS = {
		1: protobuf.Field("digest", "bytes", repeated=False, required=True),
		2: protobuf.Field("pubkey", "bytes", repeated=False, required=True),
		3: protobuf.Field("sig", "bytes", repeated=False, required=True),
	}

	def __init__(
		self,
		*,
		digest: "bytes",
		pubkey: "bytes",
		sig: "bytes",
	) -> None:
		self.digest = digest
		self.pubkey = pubkey
		self.sig = sig


# from .messages_special import *

