// This file is automatically generated from ethereum_tokens.c.mako
// DO NOT EDIT

#include "ethereum_tokens.h"
#include <string.h>
#include "ethereum.h"

#define TOKENS_COUNT 24

static const EthereumTokenInfo tokens[TOKENS_COUNT] = {
    {
        .symbol = "AAVE",
        .decimals = 18,
        .address = {.size = 20,
                    .bytes = "\x7f\xc6\x65\x00\xc8\x4a\x76\xad\x7e\x9c\x93\x43"
                             "\x7b\xfc\x5a\xc3\x3e\x2d\xda\xe9"},
        .chain_id = 1,
        .name = "",
    },
    {
        .symbol = "APE",
        .decimals = 18,
        .address = {.size = 20,
                    .bytes = "\x4d\x22\x44\x52\x80\x1a\xce\xd8\xb2\xf0\xae\xbe"
                             "\x15\x53\x79\xbb\x5d\x59\x43\x81"},
        .chain_id = 1,
        .name = "",
    },
    {
        .symbol = "AXS",
        .decimals = 18,
        .address = {.size = 20,
                    .bytes = "\xbb\x0e\x17\xef\x65\xf8\x2a\xb0\x18\xd8\xed\xd7"
                             "\x76\xe8\xdd\x94\x03\x27\xb2\x8b"},
        .chain_id = 1,
        .name = "",
    },
    {
        .symbol = "BUSD",
        .decimals = 18,
        .address = {.size = 20,
                    .bytes = "\x4f\xab\xb1\x45\xd6\x46\x52\xa9\x48\xd7\x25\x33"
                             "\x02\x3f\x6e\x7a\x62\x3c\x7c\x53"},
        .chain_id = 1,
        .name = "",
    },
    {
        .symbol = "XCN",
        .decimals = 18,
        .address = {.size = 20,
                    .bytes = "\xa2\xcd\x3d\x43\xc7\x75\x97\x8a\x96\xbd\xbf\x12"
                             "\xd7\x33\xd5\xa1\xed\x94\xfb\x18"},
        .chain_id = 1,
        .name = "",
    },
    {
        .symbol = "LINK",
        .decimals = 18,
        .address = {.size = 20,
                    .bytes = "\x51\x49\x10\x77\x1a\xf9\xca\x65\x6a\xf8\x40\xdf"
                             "\xf8\x3e\x82\x64\xec\xf9\x86\xca"},
        .chain_id = 1,
        .name = "",
    },
    {
        .symbol = "CHZ",
        .decimals = 18,
        .address = {.size = 20,
                    .bytes = "\x35\x06\x42\x4f\x91\xfd\x33\x08\x44\x66\xf4\x02"
                             "\xd5\xd9\x7f\x05\xf8\xe3\xb4\xaf"},
        .chain_id = 1,
        .name = "",
    },
    {
        .symbol = "CRO",
        .decimals = 8,
        .address = {.size = 20,
                    .bytes = "\xa0\xb7\x3e\x1f\xf0\xb8\x09\x14\xab\x6f\xe0\x44"
                             "\x4e\x65\x84\x8c\x4c\x34\x45\x0b"},
        .chain_id = 1,
        .name = "",
    },
    {
        .symbol = "DAI",
        .decimals = 18,
        .address = {.size = 20,
                    .bytes = "\x6b\x17\x54\x74\xe8\x90\x94\xc4\x4d\xa9\x8b\x95"
                             "\x4e\xed\xea\xc4\x95\x27\x1d\x0f"},
        .chain_id = 1,
        .name = "",
    },
    {
        .symbol = "MANA",
        .decimals = 18,
        .address = {.size = 20,
                    .bytes = "\x0f\x5d\x2f\xb2\x9f\xb7\xd3\xcf\xee\x44\x4a\x20"
                             "\x02\x98\xf4\x68\x90\x8c\xc9\x42"},
        .chain_id = 1,
        .name = "",
    },
    {
        .symbol = "FRAX",
        .decimals = 18,
        .address = {.size = 20,
                    .bytes = "\x85\x3d\x95\x5a\xce\xf8\x22\xdb\x05\x8e\xb8\x50"
                             "\x59\x11\xed\x77\xf1\x75\xb9\x9e"},
        .chain_id = 1,
        .name = "",
    },
    {
        .symbol = "LEO",
        .decimals = 18,
        .address = {.size = 20,
                    .bytes = "\x2a\xf5\xd2\xad\x76\x74\x11\x91\xd1\x5d\xfe\x7b"
                             "\xf6\xac\x92\xd4\xbd\x91\x2c\xa3"},
        .chain_id = 1,
        .name = "",
    },
    {
        .symbol = "STETH",
        .decimals = 18,
        .address = {.size = 20,
                    .bytes = "\xae\x7a\xb9\x65\x20\xde\x3a\x18\xe5\xe1\x11\xb5"
                             "\xea\xab\x09\x53\x12\xd7\xfe\x84"},
        .chain_id = 1,
        .name = "",
    },
    {
        .symbol = "OKB",
        .decimals = 18,
        .address = {.size = 20,
                    .bytes = "\x75\x23\x1f\x58\xb4\x32\x40\xc9\x71\x8d\xd5\x8b"
                             "\x49\x67\xc5\x11\x43\x42\xa8\x6c"},
        .chain_id = 1,
        .name = "",
    },
    {
        .symbol = "MATIC",
        .decimals = 18,
        .address = {.size = 20,
                    .bytes = "\x7d\x1a\xfa\x7b\x71\x8f\xb8\x93\xdb\x30\xa3\xab"
                             "\xc0\xcf\xc6\x08\xaa\xcf\xeb\xb0"},
        .chain_id = 1,
        .name = "",
    },
    {
        .symbol = "QNT",
        .decimals = 18,
        .address = {.size = 20,
                    .bytes = "\x4a\x22\x0e\x60\x96\xb2\x5e\xad\xb8\x83\x58\xcb"
                             "\x44\x06\x8a\x32\x48\x25\x46\x75"},
        .chain_id = 1,
        .name = "",
    },
    {
        .symbol = "SHIB",
        .decimals = 18,
        .address = {.size = 20,
                    .bytes = "\x95\xad\x61\xb0\xa1\x50\xd7\x92\x19\xdc\xf6\x4e"
                             "\x1e\x6c\xc0\x1f\x0b\x64\xc4\xce"},
        .chain_id = 1,
        .name = "",
    },
    {
        .symbol = "USDT",
        .decimals = 6,
        .address = {.size = 20,
                    .bytes = "\xda\xc1\x7f\x95\x8d\x2e\xe5\x23\xa2\x20\x62\x06"
                             "\x99\x45\x97\xc1\x3d\x83\x1e\xc7"},
        .chain_id = 1,
        .name = "",
    },
    {
        .symbol = "SAND",
        .decimals = 18,
        .address = {.size = 20,
                    .bytes = "\x38\x45\xba\xda\xde\x8e\x6d\xff\x04\x98\x20\x68"
                             "\x0d\x1f\x14\xbd\x39\x03\xa5\xd0"},
        .chain_id = 1,
        .name = "",
    },
    {
        .symbol = "USDC",
        .decimals = 6,
        .address = {.size = 20,
                    .bytes = "\xa0\xb8\x69\x91\xc6\x21\x8b\x36\xc1\xd1\x9d\x4a"
                             "\x2e\x9e\xb0\xce\x36\x06\xeb\x48"},
        .chain_id = 1,
        .name = "",
    },
    {
        .symbol = "UNI",
        .decimals = 18,
        .address = {.size = 20,
                    .bytes = "\x1f\x98\x40\xa8\x5d\x5a\xf5\xbf\x1d\x17\x62\xf9"
                             "\x25\xbd\xad\xdc\x42\x01\xf9\x84"},
        .chain_id = 1,
        .name = "",
    },
    {
        .symbol = "WBTC",
        .decimals = 8,
        .address = {.size = 20,
                    .bytes = "\x22\x60\xfa\xc5\xe5\x54\x2a\x77\x3a\xa4\x4f\xbc"
                             "\xfe\xdf\x7c\x19\x3b\xc2\xc5\x99"},
        .chain_id = 1,
        .name = "",
    },
    {
        .symbol = "ATOM",
        .decimals = 18,
        .address = {.size = 20,
                    .bytes = "\x0e\xb3\xa7\x05\xfc\x54\x72\x50\x37\xcc\x9e\x00"
                             "\x8b\xde\xde\x69\x7f\x62\xf3\x35"},
        .chain_id = 56,
        .name = "",
    },
    {
        .symbol = "WAVAX",
        .decimals = 18,
        .address = {.size = 20,
                    .bytes = "\x2c\x89\xbb\xc9\x2b\xd8\x6f\x80\x75\xd1\xde\xcc"
                             "\x58\xc7\xf4\xe0\x10\x7f\x28\x6b"},
        .chain_id = 137,
        .name = "",
    },
};

const EthereumTokenInfo UNKNOWN_TOKEN = {
    .symbol = "Wei UNKN",
    .decimals = 0,
    .address =
        {
            .size = 20,
            .bytes = "\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff"
                     "\xff\xff\xff\xff\xff\xff",
        },
    .chain_id = CHAIN_ID_UNKNOWN,
    .name = "",
};

const EthereumTokenInfo *ethereum_token_by_address(uint64_t chain_id,
                                                   const uint8_t *address) {
  if (!address) return 0;
  for (int i = 0; i < TOKENS_COUNT; i++) {
    if (chain_id == tokens[i].chain_id &&
        memcmp(address, tokens[i].address.bytes,
               sizeof(tokens[i].address.bytes)) == 0) {
      return &(tokens[i]);
    }
  }
  return &UNKNOWN_TOKEN;
}

bool is_unknown_token(const EthereumTokenInfo *token) {
  return token->chain_id == CHAIN_ID_UNKNOWN;
}
