#define VERSION_MAJOR 1
#define VERSION_MINOR 99
#define VERSION_PATCH 99

#define FIX_VERSION_MAJOR 1
#define FIX_VERSION_MINOR 99
#define FIX_VERSION_PATCH 99

#define ONEKEY_VERSION "3.1.0"
#define ONEKEY_VERSION_HEX 0x3100
