#define VERSION_MAJOR 2
#define VERSION_MINOR 99
#define VERSION_PATCH 99

#define FIX_VERSION_MAJOR 2
#define FIX_VERSION_MINOR 99
#define FIX_VERSION_PATCH 99

#define ONEKEY_VERSION "3.4.0"
#define ONEKEY_VERSION_HEX 0x3400
