#define VERSION_MAJOR 1
#define VERSION_MINOR 9
#define VERSION_PATCH 8

#define FIX_VERSION_MAJOR 1
#define FIX_VERSION_MINOR 9
#define FIX_VERSION_PATCH 0

#define ONEKEY_VERSION "2.1.1"
#define ONEKEY_VERSION_HEX 0x2101
