/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.4 */

#include "messages.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Definition for extension field wire_in */
typedef struct _wire_in_extmsg {
    bool wire_in;
} wire_in_extmsg;
#define wire_in_extmsg_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, BOOL,     wire_in,         50002)
#define wire_in_extmsg_CALLBACK NULL
#define wire_in_extmsg_DEFAULT NULL
pb_byte_t wire_in_extmsg_default[] = {0x00};
PB_BIND(wire_in_extmsg, wire_in_extmsg, 4)
const pb_extension_type_t wire_in = {
    NULL,
    NULL,
    &wire_in_extmsg_msg
};

/* Definition for extension field wire_out */
typedef struct _wire_out_extmsg {
    bool wire_out;
} wire_out_extmsg;
#define wire_out_extmsg_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, BOOL,     wire_out,        50003)
#define wire_out_extmsg_CALLBACK NULL
#define wire_out_extmsg_DEFAULT NULL
pb_byte_t wire_out_extmsg_default[] = {0x00};
PB_BIND(wire_out_extmsg, wire_out_extmsg, 4)
const pb_extension_type_t wire_out = {
    NULL,
    NULL,
    &wire_out_extmsg_msg
};

/* Definition for extension field wire_debug_in */
typedef struct _wire_debug_in_extmsg {
    bool wire_debug_in;
} wire_debug_in_extmsg;
#define wire_debug_in_extmsg_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, BOOL,     wire_debug_in,   50004)
#define wire_debug_in_extmsg_CALLBACK NULL
#define wire_debug_in_extmsg_DEFAULT NULL
pb_byte_t wire_debug_in_extmsg_default[] = {0x00};
PB_BIND(wire_debug_in_extmsg, wire_debug_in_extmsg, 4)
const pb_extension_type_t wire_debug_in = {
    NULL,
    NULL,
    &wire_debug_in_extmsg_msg
};

/* Definition for extension field wire_debug_out */
typedef struct _wire_debug_out_extmsg {
    bool wire_debug_out;
} wire_debug_out_extmsg;
#define wire_debug_out_extmsg_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, BOOL,     wire_debug_out,  50005)
#define wire_debug_out_extmsg_CALLBACK NULL
#define wire_debug_out_extmsg_DEFAULT NULL
pb_byte_t wire_debug_out_extmsg_default[] = {0x00};
PB_BIND(wire_debug_out_extmsg, wire_debug_out_extmsg, 4)
const pb_extension_type_t wire_debug_out = {
    NULL,
    NULL,
    &wire_debug_out_extmsg_msg
};

/* Definition for extension field wire_tiny */
typedef struct _wire_tiny_extmsg {
    bool wire_tiny;
} wire_tiny_extmsg;
#define wire_tiny_extmsg_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, BOOL,     wire_tiny,       50006)
#define wire_tiny_extmsg_CALLBACK NULL
#define wire_tiny_extmsg_DEFAULT NULL
pb_byte_t wire_tiny_extmsg_default[] = {0x00};
PB_BIND(wire_tiny_extmsg, wire_tiny_extmsg, 4)
const pb_extension_type_t wire_tiny = {
    NULL,
    NULL,
    &wire_tiny_extmsg_msg
};

/* Definition for extension field wire_bootloader */
typedef struct _wire_bootloader_extmsg {
    bool wire_bootloader;
} wire_bootloader_extmsg;
#define wire_bootloader_extmsg_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, BOOL,     wire_bootloader, 50007)
#define wire_bootloader_extmsg_CALLBACK NULL
#define wire_bootloader_extmsg_DEFAULT NULL
pb_byte_t wire_bootloader_extmsg_default[] = {0x00};
PB_BIND(wire_bootloader_extmsg, wire_bootloader_extmsg, 4)
const pb_extension_type_t wire_bootloader = {
    NULL,
    NULL,
    &wire_bootloader_extmsg_msg
};

/* Definition for extension field wire_no_fsm */
typedef struct _wire_no_fsm_extmsg {
    bool wire_no_fsm;
} wire_no_fsm_extmsg;
#define wire_no_fsm_extmsg_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, BOOL,     wire_no_fsm,     50008)
#define wire_no_fsm_extmsg_CALLBACK NULL
#define wire_no_fsm_extmsg_DEFAULT NULL
pb_byte_t wire_no_fsm_extmsg_default[] = {0x00};
PB_BIND(wire_no_fsm_extmsg, wire_no_fsm_extmsg, 4)
const pb_extension_type_t wire_no_fsm = {
    NULL,
    NULL,
    &wire_no_fsm_extmsg_msg
};

/* Definition for extension field unstable */
typedef struct _unstable_extmsg {
    bool unstable;
} unstable_extmsg;
#define unstable_extmsg_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, BOOL,     unstable,        50001)
#define unstable_extmsg_CALLBACK NULL
#define unstable_extmsg_DEFAULT NULL
pb_byte_t unstable_extmsg_default[] = {0x00};
PB_BIND(unstable_extmsg, unstable_extmsg, 4)
const pb_extension_type_t unstable = {
    NULL,
    NULL,
    &unstable_extmsg_msg
};

/* Definition for extension field wire_type */
typedef struct _wire_type_extmsg {
    uint32_t wire_type;
} wire_type_extmsg;
#define wire_type_extmsg_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, UINT32,   wire_type,       50002)
#define wire_type_extmsg_CALLBACK NULL
#define wire_type_extmsg_DEFAULT NULL
pb_byte_t wire_type_extmsg_default[] = {0x00};
PB_BIND(wire_type_extmsg, wire_type_extmsg, 4)
const pb_extension_type_t wire_type = {
    NULL,
    NULL,
    &wire_type_extmsg_msg
};

/* Definition for extension field experimental */
typedef struct _experimental_extmsg {
    bool experimental;
} experimental_extmsg;
#define experimental_extmsg_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, BOOL,     experimental,    52001)
#define experimental_extmsg_CALLBACK NULL
#define experimental_extmsg_DEFAULT NULL
pb_byte_t experimental_extmsg_default[] = {0x00};
PB_BIND(experimental_extmsg, experimental_extmsg, 4)
const pb_extension_type_t experimental = {
    NULL,
    NULL,
    &experimental_extmsg_msg
};



