/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.4 */

#include "messages-management.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(Initialize, Initialize, AUTO)


PB_BIND(GetFeatures, GetFeatures, AUTO)


PB_BIND(Features, Features, 2)


PB_BIND(LockDevice, LockDevice, AUTO)


PB_BIND(EndSession, EndSession, AUTO)


PB_BIND(ApplySettings, ApplySettings, 2)


PB_BIND(ApplyFlags, ApplyFlags, AUTO)


PB_BIND(ChangePin, ChangePin, AUTO)


PB_BIND(ChangeWipeCode, ChangeWipeCode, AUTO)


PB_BIND(SdProtect, SdProtect, AUTO)


PB_BIND(Ping, Ping, 2)


PB_BIND(Cancel, Cancel, AUTO)


PB_BIND(GetEntropy, GetEntropy, AUTO)


PB_BIND(Entropy, Entropy, 2)


PB_BIND(WipeDevice, WipeDevice, AUTO)


PB_BIND(LoadDevice, LoadDevice, 2)


PB_BIND(ResetDevice, ResetDevice, AUTO)


PB_BIND(BackupDevice, BackupDevice, AUTO)


PB_BIND(EntropyRequest, EntropyRequest, AUTO)


PB_BIND(EntropyAck, EntropyAck, AUTO)


PB_BIND(RecoveryDevice, RecoveryDevice, AUTO)


PB_BIND(WordRequest, WordRequest, AUTO)


PB_BIND(WordAck, WordAck, AUTO)


PB_BIND(SetU2FCounter, SetU2FCounter, AUTO)


PB_BIND(GetNextU2FCounter, GetNextU2FCounter, AUTO)


PB_BIND(NextU2FCounter, NextU2FCounter, AUTO)


PB_BIND(DoPreauthorized, DoPreauthorized, AUTO)


PB_BIND(PreauthorizedRequest, PreauthorizedRequest, AUTO)


PB_BIND(CancelAuthorization, CancelAuthorization, AUTO)


PB_BIND(BixinSeedOperate, BixinSeedOperate, 2)


PB_BIND(BixinMessageSE, BixinMessageSE, 2)


PB_BIND(BixinOutMessageSE, BixinOutMessageSE, 2)


PB_BIND(BixinReboot, BixinReboot, AUTO)


PB_BIND(BixinBackupRequest, BixinBackupRequest, AUTO)


PB_BIND(BixinBackupAck, BixinBackupAck, 2)


PB_BIND(BixinRestoreRequest, BixinRestoreRequest, 2)


PB_BIND(BixinRestoreAck, BixinRestoreAck, 2)


PB_BIND(BixinVerifyDeviceRequest, BixinVerifyDeviceRequest, 2)


PB_BIND(BixinVerifyDeviceAck, BixinVerifyDeviceAck, 2)


PB_BIND(BixinWhiteListRequest, BixinWhiteListRequest, AUTO)


PB_BIND(BixinWhiteListAck, BixinWhiteListAck, 2)


PB_BIND(BixinLoadDevice, BixinLoadDevice, 2)


PB_BIND(BixinBackupDevice, BixinBackupDevice, AUTO)


PB_BIND(BixinBackupDeviceAck, BixinBackupDeviceAck, AUTO)


PB_BIND(FactorySet, FactorySet, AUTO)


PB_BIND(DeviceInfoSettings, DeviceInfoSettings, AUTO)


PB_BIND(GetDeviceInfo, GetDeviceInfo, AUTO)


PB_BIND(DeviceInfo, DeviceInfo, AUTO)


PB_BIND(ReadSEPublicKey, ReadSEPublicKey, AUTO)


PB_BIND(SEPublicKey, SEPublicKey, AUTO)


PB_BIND(WriteSEPublicCert, WriteSEPublicCert, 2)


PB_BIND(ReadSEPublicCert, ReadSEPublicCert, AUTO)


PB_BIND(SEPublicCert, SEPublicCert, 2)


PB_BIND(SpiFlashWrite, SpiFlashWrite, 2)


PB_BIND(SpiFlashRead, SpiFlashRead, AUTO)


PB_BIND(SpiFlashData, SpiFlashData, 2)


PB_BIND(SESignMessage, SESignMessage, 2)


PB_BIND(SEMessageSignature, SEMessageSignature, AUTO)












