	// This file is automatically generated by messages_map.py -- DO NOT EDIT!

	// in messages


	// out messages

	{ 'n', 'o', MessageType_MessageType_Features,              Features_fields,              0 },

	// debug in messages


	// debug out messages

