#ifndef __POLKADOT_SUBSTRATE_COIN_H__
#define __POLKADOT_SUBSTRATE_COIN_H__

// Coin Specific
#define SUPPORTED_TX_VERSION_CURRENT 19
#define SUPPORTED_TX_VERSION_PREVIOUS (19 - 1)
#define SUPPORTED_SPEC_VERSION (9360 + 0)
#define SUPPORTED_MINIMUM_SPEC_VERSION 9360

#define COIN_AMOUNT_DECIMAL_PLACES 10
#define COIN_AMOUNT_DECIMAL_PLACES_12 12
#define COIN_AMOUNT_DECIMAL_PLACES_18 18
#define COIN_TICKER " DOT"
#define KUSAMA_COIN_TICKER " KSM"
#define WESTEND_COIN_TICKER " WND"
#define ASTAR_COIN_TICKER " ASTR"
#define JOY_COIN_TICKER " JOY"
#define MANTA_COIN_TICKER " MANTA"

#endif
