#ifndef __POLKADOT_SUBSTRATE_COIN_H__
#define __POLKADOT_SUBSTRATE_COIN_H__

// Coin Specific
#define SUPPORTED_TX_VERSION_CURRENT 26
#define SUPPORTED_TX_VERSION_CURRENT_MANTA 10
#define SUPPORTED_TX_VERSION_PREVIOUS (26 - 1)
#define SUPPORTED_SPEC_VERSION (1002006)
#define SUPPORTED_MINIMUM_SPEC_VERSION_CURRENT 4720  // v26
#define SUPPORTED_MINIMUM_SPEC_VERSION_PREVIOUS 90   // v25

#define COIN_AMOUNT_DECIMAL_PLACES 10
#define COIN_AMOUNT_DECIMAL_PLACES_12 12
#define COIN_AMOUNT_DECIMAL_PLACES_18 18
#define COIN_TICKER " DOT"
#define KUSAMA_COIN_TICKER " KSM"
#define WESTEND_COIN_TICKER " WND"
#define ASTAR_COIN_TICKER " ASTR"
#define JOY_COIN_TICKER " JOY"
#define MANTA_COIN_TICKER " MANTA"
#define BIFROST_COIN_TICKER " BNC"
#define HYDRATION_COIN_TICKER " HDX"
#endif
