/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.5 */

#include "messages.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(Initialize, Initialize, AUTO)


PB_BIND(GetFeatures, GetFeatures, AUTO)


PB_BIND(Features, Features, 2)


PB_BIND(Ping, Ping, 2)


PB_BIND(Success, Success, 2)


PB_BIND(Failure, Failure, 2)


PB_BIND(WipeDevice, WipeDevice, AUTO)


PB_BIND(ButtonRequest, ButtonRequest, AUTO)


PB_BIND(ButtonAck, ButtonAck, AUTO)


PB_BIND(FirmwareErase, FirmwareErase, AUTO)


PB_BIND(FirmwareRequest, FirmwareRequest, AUTO)


PB_BIND(FirmwareErase_ex, FirmwareErase_ex, AUTO)


PB_BIND(FirmwareUpload, FirmwareUpload, AUTO)


PB_BIND(Reboot, Reboot, AUTO)


PB_BIND(FirmwareUpdateEmmc, FirmwareUpdateEmmc, 2)


PB_BIND(EmmcFixPermission, EmmcFixPermission, AUTO)


PB_BIND(EmmcPath, EmmcPath, AUTO)


PB_BIND(EmmcPathInfo, EmmcPathInfo, 2)


PB_BIND(EmmcFile, EmmcFile, 2)


PB_BIND(EmmcFileRead, EmmcFileRead, 2)


PB_BIND(EmmcFileWrite, EmmcFileWrite, 2)


PB_BIND(EmmcFileDelete, EmmcFileDelete, 2)


PB_BIND(EmmcDir, EmmcDir, 2)


PB_BIND(EmmcDirList, EmmcDirList, 2)


PB_BIND(EmmcDirMake, EmmcDirMake, 2)


PB_BIND(EmmcDirRemove, EmmcDirRemove, 2)


PB_BIND(DeviceInfoSettings, DeviceInfoSettings, AUTO)


PB_BIND(GetDeviceInfo, GetDeviceInfo, AUTO)


PB_BIND(DeviceInfo, DeviceInfo, AUTO)


PB_BIND(ReadSEPublicKey, ReadSEPublicKey, AUTO)


PB_BIND(SEPublicKey, SEPublicKey, AUTO)


PB_BIND(WriteSEPublicCert, WriteSEPublicCert, 2)


PB_BIND(ReadSEPublicCert, ReadSEPublicCert, AUTO)


PB_BIND(SEPublicCert, SEPublicCert, 2)


PB_BIND(SESignMessage, SESignMessage, 2)


PB_BIND(SEMessageSignature, SEMessageSignature, AUTO)







