# Automatically generated by pb2py
# fmt: off
import protobuf as p

from .PubKey import PubKey

if __debug__:
    try:
        from typing import Dict, List  # noqa: F401
        from typing_extensions import Literal  # noqa: F401
    except ImportError:
        pass


class Basepoints(p.MessageType):
    MESSAGE_WIRE_TYPE = 852

    def __init__(
        self,
        revocation: PubKey = None,
        payment: PubKey = None,
        htlc: PubKey = None,
        delayed_payment: PubKey = None,
        funding_pubkey: PubKey = None,
    ) -> None:
        self.revocation = revocation
        self.payment = payment
        self.htlc = htlc
        self.delayed_payment = delayed_payment
        self.funding_pubkey = funding_pubkey

    @classmethod
    def get_fields(cls) -> Dict:
        return {
            1: ('revocation', PubKey, 0),
            2: ('payment', PubKey, 0),
            3: ('htlc', PubKey, 0),
            4: ('delayed_payment', PubKey, 0),
            5: ('funding_pubkey', PubKey, 0),
        }
