# Automatically generated by pb2py
# fmt: off
import protobuf as p

if __debug__:
    try:
        from typing import Dict, List  # noqa: F401
        from typing_extensions import Literal  # noqa: F401
    except ImportError:
        pass


class DeviceInfoSettings(p.MessageType):
    MESSAGE_WIRE_TYPE = 10001

    def __init__(
        self,
        *,
        serial_no: str = None,
        cpu_info: str = None,
        pre_firmware: str = None,
    ) -> None:
        self.serial_no = serial_no
        self.cpu_info = cpu_info
        self.pre_firmware = pre_firmware

    @classmethod
    def get_fields(cls) -> Dict:
        return {
            1: ('serial_no', p.UnicodeType, None),
            2: ('cpu_info', p.UnicodeType, None),
            3: ('pre_firmware', p.UnicodeType, None),
        }
