# Automatically generated by pb2py
# fmt: off
import protobuf as p

from .FactorySet import FactorySet

if __debug__:
    try:
        from typing import Dict, List  # noqa: F401
        from typing_extensions import Literal  # noqa: F401
    except ImportError:
        pass


class DeviceInfoSettings(p.MessageType):
    MESSAGE_WIRE_TYPE = 10001

    def __init__(
        self,
        *,
        serial: FactorySet,
    ) -> None:
        self.serial = serial

    @classmethod
    def get_fields(cls) -> Dict:
        return {
            1: ('serial', FactorySet, p.FLAG_REQUIRED),
        }
