# Automatically generated by pb2py
# fmt: off
import protobuf as p

from .Secret import Secret

if __debug__:
    try:
        from typing import Dict, List  # noqa: F401
        from typing_extensions import Literal  # noqa: F401
    except ImportError:
        pass


class ECDHReply(p.MessageType):
    MESSAGE_WIRE_TYPE = 838

    def __init__(
        self,
        shared_secret: Secret = None,
    ) -> None:
        self.shared_secret = shared_secret

    @classmethod
    def get_fields(cls) -> Dict:
        return {
            1: ('shared_secret', Secret, 0),
        }
