# Automatically generated by pb2py
# fmt: off
import protobuf as p

if __debug__:
    try:
        from typing import Dict, List  # noqa: F401
        from typing_extensions import Literal  # noqa: F401
    except ImportError:
        pass


class Ed25519Signature(p.MessageType):
    MESSAGE_WIRE_TYPE = 1010

    def __init__(
        self,
        *,
        sig: bytes,
    ) -> None:
        self.sig = sig

    @classmethod
    def get_fields(cls) -> Dict:
        return {
            1: ('sig', p.BytesType, p.FLAG_REQUIRED),
        }
