# Automatically generated by pb2py
# fmt: off
import protobuf as p

if __debug__:
    try:
        from typing import Dict, List  # noqa: F401
        from typing_extensions import Literal  # noqa: F401
    except ImportError:
        pass


class EthereumSignMessageEIP712(p.MessageType):
    MESSAGE_WIRE_TYPE = 10200

    def __init__(
        self,
        *,
        address_n: List[int] = None,
        domain_hash: bytes = None,
        message_hash: bytes = None,
    ) -> None:
        self.address_n = address_n if address_n is not None else []
        self.domain_hash = domain_hash
        self.message_hash = message_hash

    @classmethod
    def get_fields(cls) -> Dict:
        return {
            1: ('address_n', p.UVarintType, p.FLAG_REPEATED),
            2: ('domain_hash', p.BytesType, None),
            3: ('message_hash', p.BytesType, None),
        }
