# Automatically generated by pb2py
# fmt: off
if False:
    from typing_extensions import Literal

SeedEncExportType_NO = 0  # type: Literal[0]
SeedEncExportType_YES = 1  # type: Literal[1]
MnemonicPlainExportType_YES = 2  # type: Literal[2]
