# Automatically generated by pb2py
# fmt: off
import protobuf as p

from .ExtPubKey import ExtPubKey

if __debug__:
    try:
        from typing import Dict, List  # noqa: F401
        from typing_extensions import Literal  # noqa: F401
    except ImportError:
        pass


class GetExtPubKeyReply(p.MessageType):
    MESSAGE_WIRE_TYPE = 810

    def __init__(
        self,
        xpub: ExtPubKey = None,
    ) -> None:
        self.xpub = xpub

    @classmethod
    def get_fields(cls) -> Dict:
        return {
            1: ('xpub', ExtPubKey, 0),
        }
