# Automatically generated by pb2py
# fmt: off
import protobuf as p

from .PubKey import PubKey
from .Secret import Secret

if __debug__:
    try:
        from typing import Dict, List  # noqa: F401
        from typing_extensions import Literal  # noqa: F401
    except ImportError:
        pass


class GetPerCommitmentPointReply(p.MessageType):
    MESSAGE_WIRE_TYPE = 822

    def __init__(
        self,
        per_commitment_point: PubKey = None,
        old_secret: Secret = None,
    ) -> None:
        self.per_commitment_point = per_commitment_point
        self.old_secret = old_secret

    @classmethod
    def get_fields(cls) -> Dict:
        return {
            1: ('per_commitment_point', PubKey, 0),
            2: ('old_secret', Secret, 0),
        }
