# Automatically generated by pb2py
# fmt: off
import protobuf as p

if __debug__:
    try:
        from typing import Dict, List  # noqa: F401
        from typing_extensions import Literal  # noqa: F401
    except ImportError:
        pass


class NFTWriteInfo(p.MessageType):
    MESSAGE_WIRE_TYPE = 10014

    def __init__(
        self,
        *,
        index: int,
        width: int,
        height: int,
        name_zh: str = None,
        name_en: str = None,
    ) -> None:
        self.index = index
        self.width = width
        self.height = height
        self.name_zh = name_zh
        self.name_en = name_en

    @classmethod
    def get_fields(cls) -> Dict:
        return {
            1: ('index', p.UVarintType, p.FLAG_REQUIRED),
            2: ('width', p.UVarintType, p.FLAG_REQUIRED),
            3: ('height', p.UVarintType, p.FLAG_REQUIRED),
            4: ('name_zh', p.UnicodeType, None),
            5: ('name_en', p.UnicodeType, None),
        }
