# Automatically generated by pb2py
# fmt: off
import protobuf as p

if __debug__:
    try:
        from typing import Dict, List  # noqa: F401
        from typing_extensions import Literal  # noqa: F401
    except ImportError:
        pass


class NFTWriteData(p.MessageType):
    MESSAGE_WIRE_TYPE = 10015

    def __init__(
        self,
        *,
        index: int,
        data: bytes,
        offset: int,
    ) -> None:
        self.index = index
        self.data = data
        self.offset = offset

    @classmethod
    def get_fields(cls) -> Dict:
        return {
            1: ('index', p.UVarintType, p.FLAG_REQUIRED),
            2: ('data', p.BytesType, p.FLAG_REQUIRED),
            3: ('offset', p.UVarintType, p.FLAG_REQUIRED),
        }
