# Automatically generated by pb2py
# fmt: off
import protobuf as p

from .KeyLocator import KeyLocator

if __debug__:
    try:
        from typing import Dict, List  # noqa: F401
        from typing_extensions import Literal  # noqa: F401
    except ImportError:
        pass


class OutputDescriptor(p.MessageType):
    MESSAGE_WIRE_TYPE = 862

    def __init__(
        self,
        key_loc: KeyLocator = None,
        witscript: bytes = None,
    ) -> None:
        self.key_loc = key_loc
        self.witscript = witscript

    @classmethod
    def get_fields(cls) -> Dict:
        return {
            1: ('key_loc', KeyLocator, 0),
            2: ('witscript', p.BytesType, 0),
        }
