# Automatically generated by pb2py
# fmt: off
import protobuf as p

from .Basepoints import Basepoints
from .ChannelNonce import ChannelNonce
from .NodeId import NodeId
from .Outpoint import Outpoint

if __debug__:
    try:
        from typing import Dict, List  # noqa: F401
        from typing_extensions import Literal  # noqa: F401
    except ImportError:
        pass


class ReadyChannelRequest(p.MessageType):
    MESSAGE_WIRE_TYPE = 813

    def __init__(
        self,
        node_id: NodeId = None,
        channel_nonce: ChannelNonce = None,
        is_outbound: bool = None,
        channel_value_sat: int = None,
        push_value_msat: int = None,
        funding_outpoint: Outpoint = None,
        local_to_self_delay: int = None,
        local_shutdown_script: bytes = None,
        remote_basepoints: Basepoints = None,
        remote_to_self_delay: int = None,
        remote_shutdown_script: bytes = None,
        option_static_remotekey: bool = None,
    ) -> None:
        self.node_id = node_id
        self.channel_nonce = channel_nonce
        self.is_outbound = is_outbound
        self.channel_value_sat = channel_value_sat
        self.push_value_msat = push_value_msat
        self.funding_outpoint = funding_outpoint
        self.local_to_self_delay = local_to_self_delay
        self.local_shutdown_script = local_shutdown_script
        self.remote_basepoints = remote_basepoints
        self.remote_to_self_delay = remote_to_self_delay
        self.remote_shutdown_script = remote_shutdown_script
        self.option_static_remotekey = option_static_remotekey

    @classmethod
    def get_fields(cls) -> Dict:
        return {
            1: ('node_id', NodeId, 0),
            2: ('channel_nonce', ChannelNonce, 0),
            3: ('is_outbound', p.BoolType, 0),
            4: ('channel_value_sat', p.UVarintType, 0),
            5: ('push_value_msat', p.UVarintType, 0),
            6: ('funding_outpoint', Outpoint, 0),
            7: ('local_to_self_delay', p.UVarintType, 0),
            8: ('local_shutdown_script', p.BytesType, 0),
            9: ('remote_basepoints', Basepoints, 0),
            10: ('remote_to_self_delay', p.UVarintType, 0),
            11: ('remote_shutdown_script', p.BytesType, 0),
            12: ('option_static_remotekey', p.BoolType, 0),
        }
