# Automatically generated by pb2py
# fmt: off
if __debug__:
    try:
        from typing_extensions import Literal  # noqa: F401
    except ImportError:
        pass

Gen: Literal[0] = 0
EncExport: Literal[1] = 1
EncImport: Literal[2] = 2
