# Automatically generated by pb2py
# fmt: off
import protobuf as p

if __debug__:
    try:
        from typing import Dict, List  # noqa: F401
        from typing_extensions import Literal  # noqa: F401
    except ImportError:
        pass


class SEMessageSignature(p.MessageType):
    MESSAGE_WIRE_TYPE = 10013

    def __init__(
        self,
        *,
        signature: bytes,
    ) -> None:
        self.signature = signature

    @classmethod
    def get_fields(cls) -> Dict:
        return {
            1: ('signature', p.BytesType, p.FLAG_REQUIRED),
        }
