# Automatically generated by pb2py
# fmt: off
import protobuf as p

if __debug__:
    try:
        from typing import Dict, List  # noqa: F401
        from typing_extensions import Literal  # noqa: F401
    except ImportError:
        pass


class SEPublicCert(p.MessageType):
    MESSAGE_WIRE_TYPE = 10008

    def __init__(
        self,
        *,
        public_cert: bytes,
    ) -> None:
        self.public_cert = public_cert

    @classmethod
    def get_fields(cls) -> Dict:
        return {
            1: ('public_cert', p.BytesType, p.FLAG_REQUIRED),
        }
