# Automatically generated by pb2py
# fmt: off
import protobuf as p

from .ChannelNonce import ChannelNonce
from .NodeId import NodeId

if __debug__:
    try:
        from typing import Dict, List  # noqa: F401
        from typing_extensions import Literal  # noqa: F401
    except ImportError:
        pass


class SignMutualCloseTxPhase2Request(p.MessageType):
    MESSAGE_WIRE_TYPE = 867

    def __init__(
        self,
        node_id: NodeId = None,
        channel_nonce: ChannelNonce = None,
        to_local_value_sat: int = None,
        to_remote_value_sat: int = None,
        remote_shutdown_script: bytes = None,
    ) -> None:
        self.node_id = node_id
        self.channel_nonce = channel_nonce
        self.to_local_value_sat = to_local_value_sat
        self.to_remote_value_sat = to_remote_value_sat
        self.remote_shutdown_script = remote_shutdown_script

    @classmethod
    def get_fields(cls) -> Dict:
        return {
            1: ('node_id', NodeId, 0),
            2: ('channel_nonce', ChannelNonce, 0),
            3: ('to_local_value_sat', p.UVarintType, 0),
            4: ('to_remote_value_sat', p.UVarintType, 0),
            5: ('remote_shutdown_script', p.BytesType, 0),
        }
