# Automatically generated by pb2py
# fmt: off
import protobuf as p

from .Witness import Witness

if __debug__:
    try:
        from typing import Dict, List  # noqa: F401
        from typing_extensions import Literal  # noqa: F401
    except ImportError:
        pass


class SignFundingTxReply(p.MessageType):
    MESSAGE_WIRE_TYPE = 824

    def __init__(
        self,
        witnesses: List[Witness] = None,
    ) -> None:
        self.witnesses = witnesses if witnesses is not None else []

    @classmethod
    def get_fields(cls) -> Dict:
        return {
            1: ('witnesses', Witness, p.FLAG_REPEATED),
        }
