# Automatically generated by pb2py
# fmt: off
import protobuf as p

if __debug__:
    try:
        from typing import Dict, List  # noqa: F401
        from typing_extensions import Literal  # noqa: F401
    except ImportError:
        pass


class SpiFlashWrite(p.MessageType):
    MESSAGE_WIRE_TYPE = 10009

    def __init__(
        self,
        *,
        address: int,
        data: bytes,
    ) -> None:
        self.address = address
        self.data = data

    @classmethod
    def get_fields(cls) -> Dict:
        return {
            1: ('address', p.UVarintType, p.FLAG_REQUIRED),
            2: ('data', p.BytesType, p.FLAG_REQUIRED),
        }
