# Automatically generated by pb2py
# fmt: off
import protobuf as p

if __debug__:
    try:
        from typing import Dict, List  # noqa: F401
        from typing_extensions import Literal  # noqa: F401
    except ImportError:
        pass


class VersionReply(p.MessageType):
    MESSAGE_WIRE_TYPE = 843

    def __init__(
        self,
        version_string: str = None,
        major: int = None,
        minor: int = None,
        patch: int = None,
        prerelease: str = None,
        build_metadata: str = None,
    ) -> None:
        self.version_string = version_string
        self.major = major
        self.minor = minor
        self.patch = patch
        self.prerelease = prerelease
        self.build_metadata = build_metadata

    @classmethod
    def get_fields(cls) -> Dict:
        return {
            1: ('version_string', p.UnicodeType, 0),
            2: ('major', p.UVarintType, 0),
            3: ('minor', p.UVarintType, 0),
            4: ('patch', p.UVarintType, 0),
            5: ('prerelease', p.UnicodeType, 0),
            6: ('build_metadata', p.UnicodeType, 0),
        }
