image: registry.gitlab.com/satoshilabs/trezor/trezor-firmware/trezor-firmware-env.nix

# Caching
.gitlab_caching: &gitlab_caching
  cache:
    key: "$CI_COMMIT_REF_SLUG"
    paths:
      - .venv/

variables:
  SDL_VIDEODRIVER: "dummy"
  XDG_RUNTIME_DIR: "/var/tmp"

# Crypto

crypto build:
  stage: build
  <<: *gitlab_caching
  needs: []
  only:
    changes:
      - .gitlab-ci.yml
      - ci/**/*
      - crypto/**/*
  script:
    - nix-shell --run "poetry run make -C crypto"
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_SHORT_SHA"
    paths:
      - crypto/tests/aestst
      - crypto/tests/libtrezor-crypto.so
      - crypto/tests/test_check
      - crypto/tests/test_openssl
    expire_in: 1 week


# Legacy

legacy fw regular build:
  stage: build
  <<: *gitlab_caching
  needs: []
  script:
    - nix-shell --run "export MEMORY_PROTECT=1 && poetry run legacy/script/cibuild"
    - nix-shell --run "poetry run legacy/script/setup"
    - nix-shell --run "export MEMORY_PROTECT=0 && poetry run legacy/script/cibuild"
    - nix-shell --run "poetry run make -C legacy/demo"
    - mv legacy/firmware/*.bin trezor-fw-regular-$LEGACY_VERSION-$CI_COMMIT_SHORT_SHA.bin
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_SHORT_SHA"
    paths:
      - trezor-fw-regular-*.*.*-$CI_COMMIT_SHORT_SHA.bin
    expire_in: 1 week

legacy fw regular debug build:
  stage: build
  <<: *gitlab_caching
  needs: []
  variables:
    DEBUG_LINK: "1"
  script:
    - nix-shell --run "export MEMORY_PROTECT=1 && poetry run legacy/script/cibuild"
    - nix-shell --run "poetry run legacy/script/setup"
    - nix-shell --run "export MEMORY_PROTECT=0 && poetry run legacy/script/cibuild"
    - mv legacy/firmware/*.bin trezor-fw-regular-debug-$LEGACY_VERSION-$CI_COMMIT_SHORT_SHA.bin
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_SHORT_SHA"
    paths:
      - trezor-fw-regular-debug-*.*.*-$CI_COMMIT_SHORT_SHA.bin
    expire_in: 1 week

legacy fw btconly build:
  stage: build
  <<: *gitlab_caching
  needs: []
  variables:
    BITCOIN_ONLY: "1"
  script:
    - nix-shell --run "export MEMORY_PROTECT=1 && poetry run legacy/script/cibuild"
    - nix-shell --run "poetry run legacy/script/setup"
    - nix-shell --run "export MEMORY_PROTECT=0 && poetry run legacy/script/cibuild"
    - mv legacy/firmware/*.bin legacy/firmware/trezor-bitcoinonly.bin
    - nix-shell --run "poetry run ./tools/check-bitcoin-only legacy/firmware/trezor-bitcoinonly.bin"
    - mv legacy/firmware/trezor-bitcoinonly.bin trezor-fw-btconly-$LEGACY_VERSION-$CI_COMMIT_SHORT_SHA.bin
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_SHORT_SHA"
    paths:
      - trezor-fw-btconly-*.*.*-$CI_COMMIT_SHORT_SHA.bin
    expire_in: 1 week

legacy fw btconly debug build:
  stage: build
  <<: *gitlab_caching
  needs: []
  variables:
    BITCOIN_ONLY: "1"
    DEBUG_LINK: "1"
  script:
    - nix-shell --run "export MEMORY_PROTECT=1 && poetry run legacy/script/cibuild"
    - nix-shell --run "poetry run legacy/script/setup"
    - nix-shell --run "export MEMORY_PROTECT=0 && poetry run legacy/script/cibuild"
    - nix-shell --run "poetry run ./tools/check-bitcoin-only legacy/firmware/trezor.bin"
    - mv legacy/firmware/*.bin trezor-fw-btconly-debug-$LEGACY_VERSION-$CI_COMMIT_SHORT_SHA.bin
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_SHORT_SHA"
    paths:
      - trezor-fw-btconly-*.*.*-$CI_COMMIT_SHORT_SHA.bin
    expire_in: 1 week

legacy emu regular debug build:
  stage: build
  <<: *gitlab_caching
  needs: []
  variables:
    DEBUG_LINK: "1"
    EMULATOR: "1"
  script:
    - nix-shell --run "poetry run legacy/script/cibuild"
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_SHORT_SHA"
    paths:
      - legacy/firmware/*.elf
    expire_in: 1 week

legacy emu btconly debug build:
  stage: build
  <<: *gitlab_caching
  needs: []
  variables:
    BITCOIN_ONLY: "1"
    DEBUG_LINK: "1"
    EMULATOR: "1"
  script:
    - nix-shell --run "poetry run legacy/script/cibuild"
    - mv legacy/firmware/*.elf legacy/firmware/trezor-bitcoinonly.elf
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_SHORT_SHA"
    paths:
      - legacy/firmware/trezor-bitcoinonly.elf
    expire_in: 1 week
