# Automatically generated by pb2py
# fmt: off
from .. import protobuf as p

if __debug__:
    try:
        from typing import Dict, List  # noqa: F401
        from typing_extensions import Literal  # noqa: F401
    except ImportError:
        pass


class BixinRestoreRequest(p.MessageType):
    MESSAGE_WIRE_TYPE = 907

    def __init__(
        self,
        data: bytes = None,
        language: str = None,
        label: str = None,
        passphrase_protection: bool = None,
    ) -> None:
        self.data = data
        self.language = language
        self.label = label
        self.passphrase_protection = passphrase_protection

    @classmethod
    def get_fields(cls) -> Dict:
        return {
            1: ('data', p.BytesType, 0),  # required
            2: ('language', p.UnicodeType, 0),
            3: ('label', p.UnicodeType, 0),
            4: ('passphrase_protection', p.BoolType, 0),
        }
