# Automatically generated by pb2py
# fmt: off
from .. import protobuf as p

if __debug__:
    try:
        from typing import Dict, List  # noqa: F401
        from typing_extensions import Literal  # noqa: F401
    except ImportError:
        pass


class BixinLoadDevice(p.MessageType):
    MESSAGE_WIRE_TYPE = 913

    def __init__(
        self,
        mnemonics: str = None,
        language: str = None,
        label: str = None,
        skip_checksum: bool = None,
    ) -> None:
        self.mnemonics = mnemonics
        self.language = language
        self.label = label
        self.skip_checksum = skip_checksum

    @classmethod
    def get_fields(cls) -> Dict:
        return {
            1: ('mnemonics', p.UnicodeType, 0),  # required
            5: ('language', p.UnicodeType, 0),  # default=en-US
            6: ('label', p.UnicodeType, 0),
            7: ('skip_checksum', p.BoolType, 0),
        }
