# Automatically generated by pb2py
# fmt: off
from .. import protobuf as p

if __debug__:
    try:
        from typing import Dict, List  # noqa: F401
        from typing_extensions import Literal  # noqa: F401
    except ImportError:
        pass


class BixinOutMessageSE(p.MessageType):
    MESSAGE_WIRE_TYPE = 904

    def __init__(
        self,
        outmessage: bytes = None,
    ) -> None:
        self.outmessage = outmessage

    @classmethod
    def get_fields(cls) -> Dict:
        return {
            1: ('outmessage', p.BytesType, 0),
        }
