# Automatically generated by pb2py
# fmt: off
from .. import protobuf as p

if __debug__:
    try:
        from typing import Dict, List  # noqa: F401
        from typing_extensions import Literal  # noqa: F401
    except ImportError:
        pass


class BixinVerifyDeviceAck(p.MessageType):
    MESSAGE_WIRE_TYPE = 910

    def __init__(
        self,
        cert: bytes = None,
        signature: bytes = None,
    ) -> None:
        self.cert = cert
        self.signature = signature

    @classmethod
    def get_fields(cls) -> Dict:
        return {
            1: ('cert', p.BytesType, 0),  # required
            2: ('signature', p.BytesType, 0),  # required
        }
