# Automatically generated by pb2py
# fmt: off
from .. import protobuf as p

if __debug__:
    try:
        from typing import Dict, List  # noqa: F401
        from typing_extensions import Literal  # noqa: F401
    except ImportError:
        pass


class BixinBackupDeviceAck(p.MessageType):
    MESSAGE_WIRE_TYPE = 915

    def __init__(
        self,
        mnemonics: str = None,
    ) -> None:
        self.mnemonics = mnemonics

    @classmethod
    def get_fields(cls) -> Dict:
        return {
            1: ('mnemonics', p.UnicodeType, 0),  # required
        }
