# Automatically generated by pb2py
# fmt: off
from .. import protobuf as p

if __debug__:
    try:
        from typing import Dict, List  # noqa: F401
        from typing_extensions import Literal  # noqa: F401
    except ImportError:
        pass


class BixinSeedExportData(p.MessageType):

    def __init__(
        self,
        seed_exportdata: str = None,
    ) -> None:
        self.seed_exportdata = seed_exportdata

    @classmethod
    def get_fields(cls) -> Dict:
        return {
            1: ('seed_exportdata', p.UnicodeType, 0),
        }
