# Automatically generated by pb2py
# fmt: off
from .. import protobuf as p

if __debug__:
    try:
        from typing import Dict, List  # noqa: F401
        from typing_extensions import Literal  # noqa: F401
    except ImportError:
        pass


class CheckFutureSecretReply(p.MessageType):

    def __init__(
        self,
        correct: bool = None,
    ) -> None:
        self.correct = correct

    @classmethod
    def get_fields(cls) -> Dict:
        return {
            1: ('correct', p.BoolType, 0),
        }
