# Automatically generated by pb2py
# fmt: off
from .. import protobuf as p

if __debug__:
    try:
        from typing import Dict, List  # noqa: F401
        from typing_extensions import Literal  # noqa: F401
    except ImportError:
        pass


class ConfluxGetAddress(p.MessageType):
    MESSAGE_WIRE_TYPE = 10112

    def __init__(
        self,
        *,
        address_n: List[int] = None,
        show_display: bool = None,
        chain_id: int = None,
    ) -> None:
        self.address_n = address_n if address_n is not None else []
        self.show_display = show_display
        self.chain_id = chain_id

    @classmethod
    def get_fields(cls) -> Dict:
        return {
            1: ('address_n', p.UVarintType, p.FLAG_REPEATED),
            2: ('show_display', p.BoolType, None),
            3: ('chain_id', p.UVarintType, None),
        }
