# Automatically generated by pb2py
# fmt: off
from .. import protobuf as p

if __debug__:
    try:
        from typing import Dict, List  # noqa: F401
        from typing_extensions import Literal  # noqa: F401
    except ImportError:
        pass


class DigestSignature(p.MessageType):
    MESSAGE_WIRE_TYPE = 1002

    def __init__(
        self,
        *,
        pubkey: bytes,
        signature: bytes = None,
    ) -> None:
        self.pubkey = pubkey
        self.signature = signature

    @classmethod
    def get_fields(cls) -> Dict:
        return {
            1: ('pubkey', p.BytesType, p.FLAG_REQUIRED),
            2: ('signature', p.BytesType, None),
        }
