# Automatically generated by pb2py
# fmt: off
from .. import protobuf as p

from .NodeId import NodeId
from .PubKey import PubKey

if __debug__:
    try:
        from typing import Dict, List  # noqa: F401
        from typing_extensions import Literal  # noqa: F401
    except ImportError:
        pass


class ECDHRequest(p.MessageType):

    def __init__(
        self,
        node_id: NodeId = None,
        point: PubKey = None,
    ) -> None:
        self.node_id = node_id
        self.point = point

    @classmethod
    def get_fields(cls) -> Dict:
        return {
            1: ('node_id', NodeId, 0),
            2: ('point', PubKey, 0),
        }
