# Automatically generated by pb2py
# fmt: off
from .. import protobuf as p

if __debug__:
    try:
        from typing import Dict, List  # noqa: F401
        from typing_extensions import Literal  # noqa: F401
    except ImportError:
        pass


class Ed25519Nonce(p.MessageType):
    MESSAGE_WIRE_TYPE = 1008

    def __init__(
        self,
        *,
        R: bytes,
    ) -> None:
        self.R = R

    @classmethod
    def get_fields(cls) -> Dict:
        return {
            1: ('R', p.BytesType, p.FLAG_REQUIRED),
        }
