# Automatically generated by pb2py
# fmt: off
from .. import protobuf as p

if __debug__:
    try:
        from typing import Dict, List  # noqa: F401
        from typing_extensions import Literal  # noqa: F401
    except ImportError:
        pass


class Ed25519PublicKey(p.MessageType):
    MESSAGE_WIRE_TYPE = 1006

    def __init__(
        self,
        *,
        pubkey: bytes,
        privkey: bytes,
    ) -> None:
        self.pubkey = pubkey
        self.privkey = privkey

    @classmethod
    def get_fields(cls) -> Dict:
        return {
            1: ('pubkey', p.BytesType, p.FLAG_REQUIRED),
            2: ('privkey', p.BytesType, p.FLAG_REQUIRED),
        }
