# Automatically generated by pb2py
# fmt: off
if __debug__:
    try:
        from typing_extensions import Literal  # noqa: F401
    except ImportError:
        pass

SeedEncExportType_NO: Literal[0] = 0
SeedEncExportType_YES: Literal[1] = 1
MnemonicPlainExportType_YES: Literal[2] = 2
