# Automatically generated by pb2py
# fmt: off
from .. import protobuf as p

if __debug__:
    try:
        from typing import Dict, List  # noqa: F401
        from typing_extensions import Literal  # noqa: F401
    except ImportError:
        pass


class FactorySet(p.MessageType):

    def __init__(
        self,
        *,
        product: str,
        hardware_id: str,
        shell_color: str,
        factory_id: str,
        utc: str,
        serial_no: str,
    ) -> None:
        self.product = product
        self.hardware_id = hardware_id
        self.shell_color = shell_color
        self.factory_id = factory_id
        self.utc = utc
        self.serial_no = serial_no

    @classmethod
    def get_fields(cls) -> Dict:
        return {
            1: ('product', p.UnicodeType, p.FLAG_REQUIRED),
            2: ('hardware_id', p.UnicodeType, p.FLAG_REQUIRED),
            3: ('shell_color', p.UnicodeType, p.FLAG_REQUIRED),
            4: ('factory_id', p.UnicodeType, p.FLAG_REQUIRED),
            5: ('utc', p.UnicodeType, p.FLAG_REQUIRED),
            6: ('serial_no', p.UnicodeType, p.FLAG_REQUIRED),
        }
