# Automatically generated by pb2py
# fmt: off
from .. import protobuf as p

from .Basepoints import Basepoints

if __debug__:
    try:
        from typing import Dict, List  # noqa: F401
        from typing_extensions import Literal  # noqa: F401
    except ImportError:
        pass


class GetChannelBasepointsReply(p.MessageType):

    def __init__(
        self,
        basepoints: Basepoints = None,
    ) -> None:
        self.basepoints = basepoints

    @classmethod
    def get_fields(cls) -> Dict:
        return {
            1: ('basepoints', Basepoints, 0),
        }
