# Automatically generated by pb2py
# fmt: off
from .. import protobuf as p

if __debug__:
    try:
        from typing import Dict, List  # noqa: F401
        from typing_extensions import Literal  # noqa: F401
    except ImportError:
        pass


class GetEd25519Nonce(p.MessageType):
    MESSAGE_WIRE_TYPE = 1007

    def __init__(
        self,
        *,
        data: bytes,
        ctr: int,
        address_n: List[int] = None,
    ) -> None:
        self.address_n = address_n if address_n is not None else []
        self.data = data
        self.ctr = ctr

    @classmethod
    def get_fields(cls) -> Dict:
        return {
            1: ('address_n', p.UVarintType, p.FLAG_REPEATED),
            2: ('data', p.BytesType, p.FLAG_REQUIRED),
            3: ('ctr', p.UVarintType, p.FLAG_REQUIRED),
        }
