# Automatically generated by pb2py
# fmt: off
from .. import protobuf as p

if __debug__:
    try:
        from typing import Dict, List  # noqa: F401
        from typing_extensions import Literal  # noqa: F401
    except ImportError:
        pass


class KeyLocator(p.MessageType):

    def __init__(
        self,
        key_index: int = None,
    ) -> None:
        self.key_index = key_index

    @classmethod
    def get_fields(cls) -> Dict:
        return {
            2: ('key_index', p.UVarintType, 0),
        }
