# Automatically generated by pb2py
# fmt: off
from .. import protobuf as p

from .ChannelNonce import ChannelNonce
from .NodeId import NodeId

if __debug__:
    try:
        from typing import Dict, List  # noqa: F401
        from typing_extensions import Literal  # noqa: F401
    except ImportError:
        pass


class SignChannelAnnouncementRequest(p.MessageType):

    def __init__(
        self,
        node_id: NodeId = None,
        channel_nonce: ChannelNonce = None,
        channel_announcement: bytes = None,
    ) -> None:
        self.node_id = node_id
        self.channel_nonce = channel_nonce
        self.channel_announcement = channel_announcement

    @classmethod
    def get_fields(cls) -> Dict:
        return {
            1: ('node_id', NodeId, 0),
            2: ('channel_nonce', ChannelNonce, 0),
            3: ('channel_announcement', p.BytesType, 0),
        }
