# Automatically generated by pb2py
# fmt: off
from .. import protobuf as p

from .NodeId import NodeId

if __debug__:
    try:
        from typing import Dict, List  # noqa: F401
        from typing_extensions import Literal  # noqa: F401
    except ImportError:
        pass


class SignInvoiceRequest(p.MessageType):
    MESSAGE_WIRE_TYPE = 839

    def __init__(
        self,
        node_id: NodeId = None,
        data_part: bytes = None,
        human_readable_part: str = None,
    ) -> None:
        self.node_id = node_id
        self.data_part = data_part
        self.human_readable_part = human_readable_part

    @classmethod
    def get_fields(cls) -> Dict:
        return {
            1: ('node_id', NodeId, 0),
            2: ('data_part', p.BytesType, 0),
            3: ('human_readable_part', p.UnicodeType, 0),
        }
