# Automatically generated by pb2py
# fmt: off
if False:
    from typing_extensions import Literal

INVALID = 0  # type: Literal[0]
P2PKH = 1  # type: Literal[1]
P2WPKH = 3  # type: Literal[3]
P2SH_P2WPKH = 4  # type: Literal[4]
