# Automatically generated by pb2py
# fmt: off
from .. import protobuf as p

from .ChannelNonce import ChannelNonce
from .PubKey import PubKey

if __debug__:
    try:
        from typing import Dict, List  # noqa: F401
        from typing_extensions import Literal  # noqa: F401
    except ImportError:
        pass


class UnilateralCloseInfo(p.MessageType):
    MESSAGE_WIRE_TYPE = 860

    def __init__(
        self,
        channel_nonce: ChannelNonce = None,
        commitment_point: PubKey = None,
    ) -> None:
        self.channel_nonce = channel_nonce
        self.commitment_point = commitment_point

    @classmethod
    def get_fields(cls) -> Dict:
        return {
            1: ('channel_nonce', ChannelNonce, 0),
            2: ('commitment_point', PubKey, 0),
        }
