# Automatically generated by pb2py
# fmt: off
if __debug__:
    try:
        from typing_extensions import Literal  # noqa: F401
    except ImportError:
        pass

Add: Literal[0] = 0
Delete: Literal[1] = 1
Inquire: Literal[2] = 2
