name: "Prebuild checks"

on: [pull_request]

jobs:
  style-check:
    name: Style check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: cachix/install-nix-action@v13
        with:
          nix_path: nixpkgs=channel:nixos-unstable
        name: "Run style check"
      - run: nix-shell --run "poetry install"
      - run: nix-shell --run "poetry run make style_check"

  defs-check:
    name: Defs check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          submodules: "recursive"
          fetch-depth: 0
      - uses: cachix/install-nix-action@v13
        with:
          nix_path: nixpkgs=channel:nixos-unstable
        name: "Run defs check"
      - run: nix-shell --run "poetry install"
      - run: nix-shell --run "poetry run make defs_check"

  gen-check:
    name: Gen check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          submodules: "recursive"
          fetch-depth: 0
      - uses: cachix/install-nix-action@v13
        with:
          nix_path: nixpkgs=channel:nixos-unstable
        name: "Run gen check"
      - run: nix-shell --run "poetry install"
      - run: nix-shell --run "poetry run make gen_check"

  changelog-check:
    name: Changelog check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
        name: "Run check changelog"
      - run: ./ci/check_changelog.sh
